org: ranjanjyotidas
app: my-first-app
service: aws-python-simple-http-endpoint

custom:
        dockerArtifact:
                path: '.'
                dockerfile: Dockerfile
                copy: http-endpoint

package:
        exclude:
                -Jenkinsfile

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get

plugins:
        - serverless-docker-artifacts
